-- WriteLite visitor stats v1
-- Applied to Supabase project efftrxqdsrmyuaubjumh.
-- Public users can record a visit through an RPC, but visitor totals are available
-- only to authenticated profiles with is_admin = true.

create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  visited_at timestamptz not null default now()
);

alter table public.site_visits enable row level security;
revoke all on table public.site_visits from anon, authenticated;

create or replace function public.record_site_visit()
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.site_visits default values;
$$;

revoke all on function public.record_site_visit() from public;
grant execute on function public.record_site_visit() to anon, authenticated;

create or replace function public.get_admin_visitor_stats()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  london_today date := (now() at time zone 'Europe/London')::date;
  result jsonb;
begin
  if auth.uid() is null or not exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.is_admin = true
  ) then
    raise exception 'Admin access required.' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'today', count(*) filter (
      where (v.visited_at at time zone 'Europe/London')::date = london_today
    ),
    'yesterday', count(*) filter (
      where (v.visited_at at time zone 'Europe/London')::date = london_today - 1
    ),
    'last_7_days', count(*) filter (
      where (v.visited_at at time zone 'Europe/London')::date >= london_today - 6
    ),
    'all_time', count(*)
  )
  into result
  from public.site_visits v;

  return result;
end;
$$;

revoke all on function public.get_admin_visitor_stats() from public;
grant execute on function public.get_admin_visitor_stats() to authenticated;

-- A signed-in user can update their own profile, so explicitly protect the
-- is_admin flag from client-side changes.
create or replace function public.protect_profile_admin_flag()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if auth.uid() is not null and new.is_admin is distinct from old.is_admin then
    raise exception 'Admin status cannot be changed from the client.' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_profile_admin_flag on public.profiles;
create trigger protect_profile_admin_flag
before update of is_admin on public.profiles
for each row
execute function public.protect_profile_admin_flag();
