/* Novels Community — launch writer studio, reader progress and account controls */
(() => {
  'use strict';
  const SUPABASE_URL='https://efftrxqdsrmyuaubjumh.supabase.co';
  const SUPABASE_PUBLISHABLE_KEY='sb_publishable_C2qPiCHALCK9bvhFc8CpvA_Vc6tTGYo';
  const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const $=id=>document.getElementById(id);
  const state={user:null,stories:[],story:null,chapters:[],chapter:null,resumed:new Set(),injected:false};
  const text=v=>v==null?'':String(v);
  const toast=message=>{const n=$('toast');if(!n)return;n.textContent=message;n.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.classList.remove('show'),3200);};
  const words=v=>text(v).trim()?text(v).trim().split(/\s+/).length:0;

  function injectStyles(){if($('launchWriterStyles'))return;const s=document.createElement('style');s.id='launchWriterStyles';s.textContent=`
    .launch-chapter-panel{margin-top:22px}.chapter-manager-grid{display:grid;grid-template-columns:minmax(220px,.7fr) minmax(0,1.6fr);gap:20px}.chapter-list-launch{display:flex;flex-direction:column;gap:8px}.chapter-row-launch{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:11px;border:1px solid var(--border,rgba(255,255,255,.12));border-radius:12px;background:rgba(255,255,255,.025)}.chapter-row-launch.active{border-color:#8f7cff}.chapter-row-launch button.title{border:0;background:none;color:inherit;text-align:left;padding:0;cursor:pointer}.chapter-row-launch small{display:block;color:var(--muted,#9aa3b2);margin-top:3px}.chapter-row-actions{display:flex;gap:5px}.chapter-row-actions button{min-width:34px;padding:7px}.chapter-editor-launch textarea{min-height:360px}.chapter-editor-toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:center;justify-content:space-between}.chapter-editor-actions{display:flex;gap:8px;flex-wrap:wrap}.autosave-status{font-size:.82rem;color:var(--muted,#9aa3b2)}
    .reader-launch-toolbar{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end;margin:0 0 18px}.reader-launch-toolbar button{padding:7px 10px}.reader-paper.reader-light{background:#f8f4eb!important;color:#222!important}.reader-paper.reader-sepia{background:#efe2c5!important;color:#382f25!important}.reader-paper.reader-dark{background:#151923!important;color:#eef2f7!important}.reader-paper{--reader-scale:1}.reader-chapter{font-size:calc(1em * var(--reader-scale))}
    .security-panel-launch{margin-top:20px}.security-grid-launch{display:grid;grid-template-columns:1fr 1fr;gap:18px}.footer-launch-links{display:flex;gap:12px;flex-wrap:wrap}.footer-launch-links a{color:inherit;opacity:.75}.launch-dialog{border:1px solid #343b4e;border-radius:18px;background:#151923;color:#eef2f7;padding:0;max-width:min(720px,92vw);width:100%}.launch-dialog::backdrop{background:rgba(0,0,0,.72)}.launch-dialog-inner{padding:24px}.preview-copy{max-height:65vh;overflow:auto;white-space:pre-wrap;line-height:1.7}.launch-locked{padding:18px;border:1px solid rgba(187,168,255,.35);border-radius:14px;background:rgba(187,168,255,.07)}
    @media(max-width:780px){.chapter-manager-grid,.security-grid-launch{grid-template-columns:1fr}.chapter-editor-launch textarea{min-height:280px}}
  `;document.head.append(s);}

  function chapterMarkup(){return `<section class="panel launch-chapter-panel" id="chapterManagerLaunch"><div class="panel-heading"><div><span class="eyebrow">Writer studio</span><h2>Chapter manager</h2></div><span class="studio-badge">Launch editor</span></div><div class="chapter-manager-grid"><aside><label>Story<select id="chapterStoryLaunch"></select></label><div id="chapterLockedLaunch" class="launch-locked hidden"></div><div id="chapterListLaunch" class="chapter-list-launch"></div><button id="newChapterLaunch" class="button secondary full" type="button">＋ New chapter</button></aside><form id="chapterEditLaunch" class="stack-form chapter-editor-launch"><input id="chapterIdLaunch" type="hidden"><label>Chapter title<input id="chapterTitleLaunch" maxlength="160" required></label><label>Chapter text<textarea id="chapterBodyLaunch" required></textarea></label><div class="chapter-editor-toolbar"><span><strong id="chapterWordsLaunch">0</strong> words · <span id="chapterAutosaveLaunch" class="autosave-status">No local draft</span></span><div class="chapter-editor-actions"><button id="previewChapterLaunch" class="button ghost" type="button">Preview</button><button id="deleteChapterLaunch" class="button ghost" type="button">Delete</button><button class="button primary" type="submit">Save chapter</button></div></div></form></div></section>`;}
  function securityMarkup(){return `<section class="panel security-panel-launch" id="securityLaunch"><div class="panel-heading"><div><span class="eyebrow">Account</span><h2>Password & security</h2></div></div><div class="security-grid-launch"><form id="changePasswordLaunch" class="stack-form"><label>New password<input id="newPasswordLaunch" type="password" minlength="8" autocomplete="new-password" required></label><label>Confirm password<input id="confirmPasswordLaunch" type="password" minlength="8" autocomplete="new-password" required></label><button class="button primary" type="submit">Change password</button></form><div><p class="muted">Use at least 8 characters. Password reset links are sent to your account email.</p><button id="sendResetLaunch" class="button secondary" type="button">Email me a reset link</button></div></div></section>`;}

  function inject(){if(state.injected)return;injectStyles();const studio=$('writerStudio');const legacy=studio?.querySelector('.chapter-editor-panel');if(studio&&!$('chapterManagerLaunch')){if(legacy)legacy.classList.add('hidden');studio.insertAdjacentHTML('beforeend',chapterMarkup());$('chapterStoryLaunch').addEventListener('change',()=>selectStory($('chapterStoryLaunch').value));$('newChapterLaunch').onclick=newChapter;$('chapterEditLaunch').addEventListener('submit',saveChapter);$('chapterTitleLaunch').addEventListener('input',draftChanged);$('chapterBodyLaunch').addEventListener('input',draftChanged);$('previewChapterLaunch').onclick=previewChapter;$('deleteChapterLaunch').onclick=deleteChapter;}
    const grid=document.querySelector('#profileContent .profile-grid');if(grid&&!$('securityLaunch')){grid.insertAdjacentHTML('beforeend',securityMarkup());$('changePasswordLaunch').addEventListener('submit',changePassword);$('sendResetLaunch').onclick=sendReset;}
    const authForm=$('signInForm');if(authForm&&!$('forgotPasswordLaunch')){const b=document.createElement('button');b.id='forgotPasswordLaunch';b.type='button';b.className='button ghost full';b.textContent='Forgot password?';b.onclick=sendReset;authForm.append(b);}
    const paper=document.querySelector('.reader-paper');if(paper&&!$('readerLaunchToolbar')){const bar=document.createElement('div');bar.id='readerLaunchToolbar';bar.className='reader-launch-toolbar';bar.innerHTML='<button class="button ghost" data-font="-0.1">A−</button><button class="button ghost" data-font="0.1">A＋</button><button class="button ghost" data-theme="light">Light</button><button class="button ghost" data-theme="sepia">Sepia</button><button class="button ghost" data-theme="dark">Dark</button>';paper.prepend(bar);bar.addEventListener('click',readerSetting);applyReaderSettings();}
    const footer=document.querySelector('.site-footer');if(footer&&!footer.querySelector('.footer-launch-links')){const d=document.createElement('div');d.className='footer-launch-links';d.innerHTML='<a href="terms.html">Terms</a><a href="privacy.html">Privacy</a><a href="guidelines.html">Guidelines</a>';footer.append(d);}
    if(!$('chapterPreviewLaunch')){const d=document.createElement('dialog');d.id='chapterPreviewLaunch';d.className='launch-dialog';d.innerHTML='<div class="launch-dialog-inner"><div class="panel-heading"><div><span class="eyebrow">Preview</span><h2 id="previewTitleLaunch"></h2></div><button id="closePreviewLaunch" class="button ghost" type="button">Close</button></div><div id="previewBodyLaunch" class="preview-copy"></div></div>';document.body.append(d);$('closePreviewLaunch').onclick=()=>d.close();}
    document.querySelectorAll('[data-view="write"],[data-view-jump="write"]').forEach(b=>b.addEventListener('click',()=>setTimeout(loadStudio,100)));document.querySelectorAll('[data-view="profile"],[data-view-jump="profile"]').forEach(b=>b.addEventListener('click',()=>setTimeout(loadSecurity,100)));
    document.addEventListener('click',e=>{if(e.target.closest('.chapter-link,#prevChapter,#nextChapter'))setTimeout(saveProgress,450);});window.addEventListener('scroll',debounce(saveProgress,800),{passive:true});
    db.auth.onAuthStateChange(async(event,session)=>{state.user=session?.user||null;if(event==='PASSWORD_RECOVERY')setTimeout(showRecoveryPrompt,250);if(state.user){await loadStudio();await maybeResume();}});
    const signup=$('signUpForm');if(signup)signup.addEventListener('submit',e=>{const p=$('signUpPassword')?.value||'';if(p.length<8){e.preventDefault();e.stopImmediatePropagation();toast('Use at least 8 characters for your password.');}},true);
    state.injected=true;}

  function debounce(fn,ms){let t;return(...args)=>{clearTimeout(t);t=setTimeout(()=>fn(...args),ms);};}
  const autosave=debounce(()=>{if(!state.story)return;const key=`novels-draft:${state.story.id}:${$('chapterIdLaunch').value||'new'}`;localStorage.setItem(key,JSON.stringify({title:$('chapterTitleLaunch').value,content:$('chapterBodyLaunch').value,at:Date.now()}));$('chapterAutosaveLaunch').textContent='Local draft saved';},500);
  function draftChanged(){$('chapterWordsLaunch').textContent=words($('chapterBodyLaunch').value);$('chapterAutosaveLaunch').textContent='Saving local draft…';autosave();}
  async function getUser(){const {data:{session}}=await db.auth.getSession();state.user=session?.user||null;return state.user;}

  async function loadStudio(){const user=await getUser();if(!user||!$('chapterManagerLaunch'))return;const {data,error}=await db.from('stories').select('*').eq('owner_id',user.id).order('updated_at',{ascending:false});if(error)return;state.stories=data||[];const sel=$('chapterStoryLaunch');const current=state.story?.id;sel.replaceChildren();state.stories.forEach(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=s.title;sel.append(o);});if(!state.stories.length){newChapter();return;}const target=state.stories.find(s=>s.id===current)||state.stories[0];sel.value=target.id;await selectStory(target.id);}
  async function selectStory(id){state.story=state.stories.find(s=>s.id===id)||null;if(!state.story)return;const locked=state.story.slug==='balance-due';$('chapterLockedLaunch').classList.toggle('hidden',!locked);$('chapterLockedLaunch').innerHTML=locked?'<strong>Balance Due is locked.</strong><br>The published manuscript is version-controlled in GitHub. Covers, summary and metadata remain editable in the story editor above.':'';$('chapterEditLaunch').classList.toggle('hidden',locked);$('newChapterLaunch').classList.toggle('hidden',locked);if(locked){$('chapterListLaunch').replaceChildren();return;}const {data,error}=await db.from('chapters').select('*').eq('story_id',id).order('position');if(error)return toast('Could not load chapters.');state.chapters=data||[];renderChapters();if(state.chapters.length)openChapter(state.chapters[0]);else newChapter();}
  function renderChapters(){const box=$('chapterListLaunch');box.replaceChildren();state.chapters.forEach((c,i)=>{const row=document.createElement('div');row.className='chapter-row-launch'+(state.chapter?.id===c.id?' active':'');const title=document.createElement('button');title.type='button';title.className='title';title.innerHTML=`<strong>${escapeHtml(c.title)}</strong><small>Chapter ${c.position} · ${words(c.content)} words</small>`;title.onclick=()=>openChapter(c);const actions=document.createElement('div');actions.className='chapter-row-actions';const up=mini('↑',()=>moveChapter(c,-1));up.disabled=i===0;const down=mini('↓',()=>moveChapter(c,1));down.disabled=i===state.chapters.length-1;actions.append(up,down);row.append(title,actions);box.append(row);});}
  function mini(label,fn){const b=document.createElement('button');b.type='button';b.className='button ghost';b.textContent=label;b.onclick=fn;return b;}
  const escapeHtml=s=>text(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  function openChapter(c){state.chapter=c;$('chapterIdLaunch').value=c.id;$('chapterTitleLaunch').value=c.title||'';$('chapterBodyLaunch').value=c.content||'';$('chapterWordsLaunch').textContent=words(c.content);restoreDraft(c.id);renderChapters();}
  function newChapter(){state.chapter=null;$('chapterIdLaunch').value='';$('chapterTitleLaunch').value='';$('chapterBodyLaunch').value='';$('chapterWordsLaunch').textContent='0';$('chapterAutosaveLaunch').textContent='New chapter';restoreDraft('new');renderChapters();}
  function restoreDraft(id){if(!state.story)return;const key=`novels-draft:${state.story.id}:${id}`;try{const d=JSON.parse(localStorage.getItem(key)||'null');if(d&&Date.now()-d.at<1000*60*60*24*14){$('chapterTitleLaunch').value=d.title||$('chapterTitleLaunch').value;$('chapterBodyLaunch').value=d.content||$('chapterBodyLaunch').value;$('chapterWordsLaunch').textContent=words($('chapterBodyLaunch').value);$('chapterAutosaveLaunch').textContent='Recovered local draft';}else $('chapterAutosaveLaunch').textContent='No local draft';}catch{$('chapterAutosaveLaunch').textContent='No local draft';}}
  async function saveChapter(e){e.preventDefault();if(!state.story)return;const title=$('chapterTitleLaunch').value.trim(),content=$('chapterBodyLaunch').value.trim();if(!title||!content)return toast('Chapter title and text are required.');const button=e.submitter;button.disabled=true;try{let data,error;if(state.chapter){({data,error}=await db.from('chapters').update({title,content,updated_at:new Date().toISOString()}).eq('id',state.chapter.id).select().single());}else{const position=(state.chapters.at(-1)?.position||0)+1;({data,error}=await db.from('chapters').insert({story_id:state.story.id,position,title,content}).select().single());}if(error)throw error;localStorage.removeItem(`novels-draft:${state.story.id}:${state.chapter?.id||'new'}`);toast('Chapter saved.');await selectStory(state.story.id);if(data)openChapter(data);}catch(err){console.error(err);toast(err.message||'Could not save chapter.');}finally{button.disabled=false;}}
  async function moveChapter(c,direction){const {error}=await db.rpc('move_chapter',{p_chapter_id:c.id,p_direction:direction});if(error)return toast(error.message);await selectStory(state.story.id);}
  async function deleteChapter(){if(!state.chapter)return;if(!confirm(`Delete “${state.chapter.title}”? This cannot be undone.`))return;const {error}=await db.from('chapters').delete().eq('id',state.chapter.id);if(error)return toast(error.message);localStorage.removeItem(`novels-draft:${state.story.id}:${state.chapter.id}`);toast('Chapter deleted.');await selectStory(state.story.id);}
  function previewChapter(){const title=$('chapterTitleLaunch').value.trim()||'Untitled chapter',body=$('chapterBodyLaunch').value.trim();$('previewTitleLaunch').textContent=title;$('previewBodyLaunch').textContent=body||'Nothing written yet.';$('chapterPreviewLaunch').showModal();}

  function readerSetting(e){const b=e.target.closest('button');if(!b)return;let scale=Number(localStorage.getItem('novels-reader-scale')||1);if(b.dataset.font){scale=Math.min(1.5,Math.max(.8,scale+Number(b.dataset.font)));localStorage.setItem('novels-reader-scale',String(scale));}if(b.dataset.theme)localStorage.setItem('novels-reader-theme',b.dataset.theme);applyReaderSettings();}
  function applyReaderSettings(){const paper=document.querySelector('.reader-paper');if(!paper)return;const scale=Number(localStorage.getItem('novels-reader-scale')||1),theme=localStorage.getItem('novels-reader-theme')||'dark';paper.style.setProperty('--reader-scale',scale);paper.classList.remove('reader-light','reader-sepia','reader-dark');paper.classList.add(`reader-${theme}`);}
  async function currentStoryFromUrl(){const slug=new URLSearchParams(location.search).get('story');if(!slug)return null;const {data}=await db.from('stories').select('id,slug').eq('slug',slug).maybeSingle();return data||null;}
  async function saveProgress(){const user=await getUser();const view=$('readerView');if(!user||!view?.classList.contains('active'))return;const story=await currentStoryFromUrl();if(!story)return;const links=[...document.querySelectorAll('.chapter-link')];const active=links.findIndex(x=>x.classList.contains('active'));if(active<0)return;const doc=document.documentElement;const max=Math.max(1,doc.scrollHeight-window.innerHeight);const pct=Math.min(100,Math.max(0,(window.scrollY/max)*100));await db.from('reading_progress').upsert({user_id:user.id,story_id:story.id,chapter_position:active+1,scroll_percent:Number(pct.toFixed(2)),updated_at:new Date().toISOString()},{onConflict:'user_id,story_id'});}
  async function maybeResume(){const user=await getUser();const story=await currentStoryFromUrl();if(!user||!story||state.resumed.has(story.id))return;const {data}=await db.from('reading_progress').select('*').eq('user_id',user.id).eq('story_id',story.id).maybeSingle();if(!data)return;state.resumed.add(story.id);setTimeout(()=>{const links=[...document.querySelectorAll('.chapter-link')];const target=links[data.chapter_position-1];if(target){target.click();setTimeout(()=>window.scrollTo({top:Math.max(0,(document.documentElement.scrollHeight-window.innerHeight)*(Number(data.scroll_percent||0)/100)),behavior:'smooth'}),250);toast('Resumed where you left off.');}},700);}

  async function sendReset(){const email=$('signInEmail')?.value.trim()||state.user?.email;if(!email)return toast('Enter your email address first.');const redirectTo=`${location.origin}${location.pathname}`;const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo});if(error)return toast(error.message);toast('Password reset email sent.');}
  async function changePassword(e){e.preventDefault();const a=$('newPasswordLaunch').value,b=$('confirmPasswordLaunch').value;if(a.length<8)return toast('Use at least 8 characters.');if(a!==b)return toast('Passwords do not match.');const {error}=await db.auth.updateUser({password:a});if(error)return toast(error.message);e.target.reset();toast('Password changed.');}
  function showRecoveryPrompt(){const p=prompt('Enter a new password (at least 8 characters):');if(!p)return;if(p.length<8)return toast('Password must be at least 8 characters.');db.auth.updateUser({password:p}).then(({error})=>toast(error?error.message:'Password changed.'));}
  async function loadSecurity(){await getUser();}

  async function boot(){inject();await getUser();if(state.user){await loadStudio();await maybeResume();}setInterval(()=>{if(document.visibilityState==='visible')maybeResume();},15000);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
